### ISSUE TITLE
r1.8 for 1.10.2 prevents "/help" on dedicated server from executing, gives the following error in console.

### ISSUE THREAD

**Issue by kreezxil** [yrsegal/PSIonic-Upgrades#5]
```
[13:46:09] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
        at wiresegal.psionup.common.command.CommandPsiLearn.func_71518_a(CommandPsiLearn.kt:126) ~[CommandPsiLearn.class:?]
        at com.matthewprenger.helpfixer.HelpFixer$1.func_184900_a(HelpFixer.java:47) ~[HelpFixer$1.class:1.3.14]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:73) ~[al.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:103) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:82) [k.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:913) [me.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:892) [me.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [im.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [im.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [fl$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_92]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
        at net.minecraft.util.Util.func_181617_a(SourceFile:45) [h.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) [ld.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_92]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_92]
        ... 18 more
Caused by: java.lang.NullPointerException
```

**Comment by yrsegal** [comment]
I see, bleh. I'll fix it.
